DROP TABLE IF EXISTS price_ticks CASCADE;
DROP TABLE IF EXISTS alert_events CASCADE;
DROP TABLE IF EXISTS alerts CASCADE;
DROP TYPE IF EXISTS alert_type;
DROP TABLE IF EXISTS watchlist_items CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
